// LOCALHOST
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/63c2fe8cb94baacb1ceb2d3b
###
GET http://localhost:8080/contacts/63c2fe8cb94baacb1ceb2d3c
###
GET http://localhost:8080/contacts/63c2fe8cb94baacb1ceb2d3d
###
GET http://localhost:8080/contacts/63c2fe8cb94baacb1ceb2d3e
###
GET http://localhost:8080/contacts/63c2fe8cb94baacb1ceb2d3f

// PRODUCTION Deploy https://cse341-dwbb.onrender.com
###
GET https://cse341-dwbb.onrender.com/contacts
###
GET https://cse341-dwbb.onrender.com/contacts/63c2fe8cb94baacb1ceb2d3b
###
GET https://cse341-dwbb.onrender.com/contacts/63c2fe8cb94baacb1ceb2d3c
###
GET https://cse341-dwbb.onrender.com/contacts/63c2fe8cb94baacb1ceb2d3d
###
GET https://cse341-dwbb.onrender.com/contacts/63c2fe8cb94baacb1ceb2d3e
###
GET https://cse341-dwbb.onrender.com/contacts/63c2fe8cb94baacb1ceb2d3f